<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.authentication.failure_handler' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Http/Authentication/DefaultAuthenticationFailureHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php';

return $this->privates['sylius.authentication.failure_handler'] = new \Sylius\Bundle\UserBundle\Authentication\AuthenticationFailureHandler(($this->services['http_kernel'] ?? $this->getHttpKernelService()), ($this->privates['security.http_utils'] ?? $this->load('getSecurity_HttpUtilsService.php')), [], ($this->privates['monolog.logger.security'] ?? $this->load('getMonolog_Logger_SecurityService.php')));
