<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.validator.unique.registered_user' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Constraints/RegisteredUserValidator.php';

return $this->services['sylius.validator.unique.registered_user'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\RegisteredUserValidator(($this->services['sylius.repository.customer'] ?? $this->load('getSylius_Repository_CustomerService.php')));
