<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.failure_handler.shop.form_login' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Http/Authentication/CustomAuthenticationFailureHandler.php';

return $this->privates['security.authentication.failure_handler.shop.form_login'] = new \Symfony\Component\Security\Http\Authentication\CustomAuthenticationFailureHandler(($this->privates['sylius.authentication.failure_handler'] ?? $this->load('getSylius_Authentication_FailureHandlerService.php')), ['login_path' => 'sylius_shop_login', 'failure_path' => 'sylius_shop_login', 'failure_forward' => false, 'failure_path_parameter' => '_failure_path']);
